// :core — the platform-agnostic Kotlin port core, mirroring appletv/HexStackerKit.
//
// Kotlin Multiplatform (jvm + android targets) on purpose: the JS engine binding
// (Zipline's QuickJs) ships per-platform natives, so the jvm() target runs the golden
// conformance tests on the desktop JVM (no emulator) while the android target
// hands the app the correct .so files. A plain kotlin-jvm module would leak
// desktop natives into the Android app.
plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.kotlin.serialization)
}

kotlin {
    jvm()
    androidLibrary {
        namespace = "com.hexstacker.core"
        compileSdk = 37
        minSdk = 28
    }
    jvmToolchain(17)

    sourceSets {
        // Intermediate source set shared by jvm + android for code that needs
        // OkHttp (which has no common KMP metadata). RelayClient lives here so the
        // jvm() target runs it in tests and the android target ships it.
        val jvmAndroidMain = create("jvmAndroidMain") { dependsOn(commonMain.get()) }
        jvmMain { dependsOn(jvmAndroidMain) }
        androidMain { dependsOn(jvmAndroidMain) }

        commonMain {
            dependencies {
                implementation(libs.zipline)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
            }
        }
        jvmAndroidMain.dependencies {
            implementation(libs.okhttp)
        }
        jvmTest {
            dependencies {
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.core)
            }
        }
    }
}

// Point the JVM tests at the canonical native core bundle (dist/partycore.js,
// produced by `npm run build` at the repo root — the same iife the Android app
// will load into QuickJS from assets). Passed as an absolute path so the test is
// hermetic regardless of the test working directory.
tasks.withType<Test>().configureEach {
    // QuickJS parses decimal LITERALS with a locale-dependent strtod, so a developer or CI
    // shell in a comma-decimal locale makes `1.5` evaluate to 1 and silently corrupts every
    // decimal constant in the engine bundle. Pin the C locale for the test JVM so the
    // goldens do not depend on whoever is running them. EngineBridge asserts the same
    // invariant at runtime, which is what protects a real device.
    environment("LC_ALL", "C")
    environment("LC_NUMERIC", "C")
    val repoRoot = rootProject.layout.projectDirectory.dir("..")
    // Every repo file these tests read, as system property -> repo-relative path. ONE list,
    // because the systemProperty wiring and the input declaration below it must not drift:
    // a fixture added here becomes both automatically.
    val fixtures = linkedMapOf(
        "hexcore.bundle" to "dist/partycore.js",
        // Cross-engine conformance: the frame() golden driver bundle + the V8-recorded
        // golden it must reproduce when run in QuickJS.
        "hexcore.frametest.bundle" to "dist/partycore-frame-test.js",
        "hexcore.frametest.golden" to "tests/fixtures/partycore-frame-golden.json",
        // Cross-platform room conformance: the op log + expected snapshots the SAME
        // RoomCore module produces in Node and in JavaScriptCore on tvOS.
        "hexcore.roomcore.golden" to "tests/fixtures/room-core-golden.json",
        // Packed native wire format: the payloads + expected frames recorded by the JS
        // reference decoder, which PackedFrameTest replays through the Kotlin port.
        "hexcore.packed.golden" to "tests/fixtures/partycore-packed-golden.json",
        // Render-math parity: the canonical web JS the Kotlin ports must match byte-for-byte.
        "hexcore.web.constants" to "server/constants.js",
        "hexcore.web.theme" to "public/shared/theme.js",
        "hexcore.web.canvasutils" to "public/shared/CanvasUtils.js",
    ).mapValues { (_, path) -> repoRoot.file(path) }

    fixtures.forEach { (property, file) -> systemProperty(property, file.asFile.absolutePath) }
    // Opt-in live relay smoke test: ./gradlew :core:jvmTest -Dhexcore.relay.live=1
    systemProperty("hexcore.relay.live", System.getProperty("hexcore.relay.live") ?: "0")

    // A systemProperty is NOT a file input. Without this, rebuilding the bundle or editing a
    // golden leaves the task UP-TO-DATE and the cross-port gate silently does not run for
    // exactly the edit it exists to catch (found by rebuilding dist/partycore.js and getting
    // UP-TO-DATE out of :core:jvmTest).
    //
    // `files`, not `file`: dist/ is generated by `npm run build` and is untracked, so a fresh
    // checkout has none of it, and a single-file input would fail the task outright instead of
    // letting the test report which fixture is missing. NONE sensitivity because only the
    // CONTENT is read; the paths are absolute and machine-specific anyway.
    inputs.files(fixtures.values)
        .withPropertyName("hexcoreFixtures")
        .withPathSensitivity(PathSensitivity.NONE)

    // dist/partycore.js is also an OUTPUT of :tv:buildEngineBundle (the fresh-clone
    // convenience that regenerates it), so declaring it as an input above makes Gradle
    // demand an order between the two: without this, `./gradlew :core:jvmTest
    // :tv:assembleDebug` fails validation, and that is the CI invocation.
    //
    // mustRunAfter, not dependsOn: CI builds the bundles with `npm run build:native`
    // before Gradle runs at all, and these tests are meant to READ a bundle that is
    // already built rather than trigger a build of it. That is the contract they had
    // before this input existed; all this adds is "if both are in one graph, bundle first".
    mustRunAfter(":tv:buildEngineBundle")
}
